
import type { CommunityPost } from '@/types';

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 'post1',
    user: {
      name: 'Market Maven',
      username: '@MarketMaven123',
      avatarUrl: 'https://placehold.co/40x40.png?text=MM',
    },
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    content: 'Reliance Industries (RELIANCE) looking bullish after recent announcements. Expecting a breakout above 2500 levels soon. Strong volume today.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'company building',
    stockSymbol: 'RELIANCE',
    stockChangePercent: 1.54,
    tags: ['Analysis', 'Bullish', 'Reliance'],
    source: 'User Generated',
    likes: 152,
    comments: 18,
    reposts: 25,
    category: 'Fiat',
  },
  {
    id: 'post2',
    user: {
      name: 'Crypto King',
      username: '@CryptoKingETH',
      avatarUrl: 'https://placehold.co/40x40.png?text=CK',
    },
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), // 5 hours ago
    content: 'Bitcoin (BTC) facing resistance at $31k. Important level to watch. If it breaks, next target $35k. Holding my spot positions for now.',
    stockSymbol: 'BTC',
    stockChangePercent: -0.50,
    tags: ['Crypto', 'Bitcoin', 'Technical Analysis'],
    source: 'User Generated',
    likes: 289,
    comments: 45,
    reposts: 60,
    category: 'Crypto',
  },
  {
    id: 'post3',
    user: {
      name: 'Nifty Trader',
      username: '@NiftyProTrader',
      avatarUrl: 'https://placehold.co/40x40.png?text=NT',
    },
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    content: 'NIFTY 50 showing signs of consolidation around 21500. Option chain data suggests strong support at 21400 PE and resistance at 21700 CE. #NIFTY #OptionsTrading',
    tags: ['NIFTY', 'Market Update', 'Options'],
    source: 'User Generated',
    likes: 98,
    comments: 12,
    reposts: 10,
    category: 'Fiat',
  },
  {
    id: 'post_wealth_1',
    user: {
        name: 'Wealth Builder',
        username: '@WealthBuilder',
        avatarUrl: 'https://placehold.co/40x40.png?text=WB',
    },
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(), // 8 hours ago
    content: 'Just started an SIP in the Parag Parikh Flexi Cap Fund. Their strategy of investing in both domestic and international equities seems promising for long-term growth. #SIP #MutualFunds',
    stockSymbol: 'PARAGPARIKH',
    tags: ['Investing', 'Mutual Funds', 'Wealth'],
    source: 'User Generated',
    likes: 88,
    comments: 15,
    reposts: 9,
    category: 'Wealth',
  },
  {
    id: 'post4',
    user: {
      name: 'Value Investor',
      username: '@ValueSeeker',
      avatarUrl: 'https://placehold.co/40x40.png?text=VI',
    },
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    content: 'Identified a potentially undervalued small-cap stock: XYZ Ltd. Trading at a P/E of 8 with good growth prospects. Doing further research. Not financial advice.',
    imageUrl: 'https://placehold.co/600x300.png',
    imageAiHint: 'stock graph',
    stockSymbol: 'XYZLtd',
    stockChangePercent: 3.20,
    tags: ['SmallCap', 'Value Investing', 'Research'],
    source: 'User Generated',
    likes: 75,
    comments: 22,
    reposts: 5,
    category: 'Fiat',
  },
  {
    id: 'post5',
    user: {
      name: 'News Hub',
      username: '@MarketNewsBot',
      avatarUrl: 'https://placehold.co/40x40.png?text=NB',
    },
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 mins ago
    content: 'SEBI announces new framework for SME listings. Aims to boost capital formation for small and medium enterprises. Impact on specific stocks to be seen.',
    tags: ['SEBI', 'Regulation', 'Market News'],
    source: 'Aggregated News',
    likes: 110,
    comments: 5,
    reposts: 30,
    category: 'Fiat',
  },
  {
    id: 'research1',
    user: {
      name: 'InvestSmart Analysts',
      username: '@InvestSmart',
      avatarUrl: 'https://placehold.co/40x40.png?text=IS',
    },
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
    content: 'Initiating coverage on INFY with a BUY rating. Strong deal pipeline and margin improvement expected. Digital transformation tailwinds continue to provide growth opportunities.',
    stockSymbol: 'INFY',
    stockChangePercent: 1.20,
    tags: ['IT', 'Large Cap', 'Growth'],
    source: 'Research Report',
    likes: 215,
    comments: 30,
    reposts: 40,
    recommendationType: 'Buy',
    targetPrice: 1850,
    researchFirm: 'InvestSmart Securities',
    analystName: 'Rohan Sharma',
    category: 'Fiat',
  },
  {
    id: 'research2',
    user: {
      name: 'Alpha Advisors',
      username: '@AlphaAdvisors',
      avatarUrl: 'https://placehold.co/40x40.png?text=AA',
    },
    timestamp: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(), // 26 hours ago
    content: 'Reiterating HOLD on TATAMOTORS. While EV segment shows promise, increased competition and global chip shortages pose near-term challenges. Monitor Q2 results closely.',
    stockSymbol: 'TATAMOTORS',
    stockChangePercent: -0.50,
    tags: ['Auto', 'EV', 'Market Watch'],
    source: 'Analyst Update',
    likes: 150,
    comments: 15,
    reposts: 22,
    recommendationType: 'Hold',
    targetPrice: 950,
    researchFirm: 'Alpha Advisors Pvt. Ltd.',
    analystName: 'Priya Desai',
    category: 'Fiat',
  },
  {
    id: 'research3',
    user: {
      name: 'Momentum Traders Inc.',
      username: '@MomentumInc',
      avatarUrl: 'https://placehold.co/40x40.png?text=MI',
    },
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(), // 8 hours ago
    content: 'ACCUMULATE recommendation for BANKNIFTY options. Expecting volatility to pick up ahead of the RBI policy meet. Consider long straddles or strangles.',
    stockSymbol: 'BANKNIFTY', // Example, could be index or related ETF
    tags: ['Banking', 'Options Strategy', 'Volatility'],
    source: 'Trading Call',
    likes: 95,
    comments: 8,
    reposts: 12,
    recommendationType: 'Accumulate',
    researchFirm: 'Momentum Traders Inc.',
    category: 'Fiat',
  },
  {
    id: 'research_wealth_1',
    user: {
        name: 'SIM Research Desk',
        username: '@SIM_Research',
        avatarUrl: 'https://placehold.co/40x40.png?text=SR',
    },
    timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    content: 'The 10-year G-Sec bond yield is expected to remain range-bound in the near term. We recommend investors to look at bonds with 3-5 year maturity for a better risk-reward profile. #Bonds #FixedIncome',
    tags: ['Bonds', 'Research', 'Fixed Income'],
    source: 'SIM Research',
    likes: 60,
    comments: 10,
    reposts: 8,
    category: 'Wealth',
  },
  {
    id: 'research4',
    user: {
      name: 'Value Picks Research',
      username: '@ValuePicks',
      avatarUrl: 'https://placehold.co/40x40.png?text=VP',
    },
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    content: 'We recommend a SELL on ZEEENT due to increasing competitive pressures in the media landscape and stretched valuations. Upside appears limited from current levels.',
    stockSymbol: 'ZEEENT',
    stockChangePercent: -2.10,
    tags: ['Media', 'Valuation', 'Sector Outlook'],
    source: 'Equity Research',
    likes: 70,
    comments: 25,
    reposts: 8,
    recommendationType: 'Sell',
    targetPrice: 220,
    researchFirm: 'Value Picks Research',
    category: 'Fiat',
  },
  {
    id: 'post_crypto_1',
    user: {
      name: 'Crypto Trader Pro',
      username: '@CT_Pro',
      avatarUrl: 'https://placehold.co/40x40.png?text=CT',
    },
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    content: 'Solana (SOL) is showing great strength, breaking past the 15000 INR level. The ecosystem is buzzing with activity. Next resistance at 18000 INR.',
    imageUrl: 'https://placehold.co/600x350.png',
    imageAiHint: 'crypto chart abstract',
    stockSymbol: 'SOL',
    stockChangePercent: 5.2,
    tags: ['Solana', 'Altcoin', 'Bullish'],
    source: 'User Generated',
    likes: 180,
    comments: 25,
    reposts: 35,
    category: 'Crypto',
  },
  {
    id: 'post_crypto_2',
    user: {
      name: 'DeFi Degen',
      username: '@DeFiDegenLife',
      avatarUrl: 'https://placehold.co/40x40.png?text=DD',
    },
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    content: 'The ETH/BTC ratio is at a critical point. A bounce here could signal the start of a new altseason. Watching closely. #Ethereum #Bitcoin #Crypto',
    tags: ['ETH', 'BTC', 'RatioTrading'],
    source: 'User Generated',
    likes: 250,
    comments: 60,
    reposts: 55,
    category: 'Crypto',
  },
  {
    id: 'post_web3_1',
    user: {
      name: 'AI & Web3 Enthusiast',
      username: '@AIWeb3',
      avatarUrl: 'https://placehold.co/40x40.png?text=AW',
    },
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    content: 'The Render Network (RNDR) continues to be a leader in decentralized GPU rendering. The recent partnership with a major animation studio is huge news for the project. #Web3 #AI #DePIN',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'digital art creation',
    stockSymbol: 'RNDR',
    stockChangePercent: 8.1,
    tags: ['Render', 'DePIN', 'AI'],
    source: 'User Generated',
    likes: 310,
    comments: 42,
    reposts: 70,
    category: 'Web3',
  },
  {
    id: 'post_web3_2',
    user: {
      name: 'DeFi Degen',
      username: '@DeFiDegenLife',
      avatarUrl: 'https://placehold.co/40x40.png?text=DD',
    },
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    content: 'Just took out a loan on Aave v3. The efficiency and low gas fees on L2s are a game changer for DeFi. Is this the future of finance?',
    tags: ['DeFi', 'AAVE', 'Lending'],
    source: 'User Generated',
    likes: 120,
    comments: 33,
    reposts: 15,
    category: 'Web3',
  },
  {
    id: 'research_crypto_1',
    user: {
      name: 'SIM Research Desk',
      username: '@SIM_Research',
      avatarUrl: 'https://placehold.co/40x40.png?text=SR',
    },
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), // 12 hours ago
    content: 'Our latest report on Ethereum (ETH) suggests strong on-chain metrics and upcoming EIPs could lead to a re-test of previous highs. We initiate with an ACCUMULATE rating.',
    stockSymbol: 'ETH',
    stockChangePercent: -1.12,
    tags: ['Ethereum', 'Crypto Research', 'On-Chain'],
    source: 'SIM Research',
    likes: 450,
    comments: 88,
    reposts: 110,
    recommendationType: 'Accumulate',
    targetPrice: 180000,
    researchFirm: 'SIM Research',
    analystName: 'Crypto Team',
    category: 'Crypto',
  },
  {
    id: 'research_web3_1',
    user: {
      name: 'SIM Research Desk',
      username: '@SIM_Research',
      avatarUrl: 'https://placehold.co/40x40.png?text=SR',
    },
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    content: 'In-depth analysis of the Aave protocol. The move to V3 has significantly improved capital efficiency. We see strong long-term potential for the AAVE token as a blue-chip DeFi asset. Rating: BUY.',
    stockSymbol: 'AAVE',
    stockChangePercent: 2.81,
    tags: ['DeFi', 'AAVE', 'Web3 Research'],
    source: 'SIM Research',
    likes: 320,
    comments: 55,
    reposts: 75,
    recommendationType: 'Buy',
    targetPrice: 10000, // approx $120
    researchFirm: 'SIM Research',
    analystName: 'Web3 Division',
    category: 'Web3',
  },
  {
    id: 'post6',
    user: {
      name: 'PharmaAnalyst',
      username: '@PharmaPro',
      avatarUrl: 'https://placehold.co/40x40.png?text=PA',
    },
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    content: 'Sun Pharma (SUNPHARMA) results are out. Decent growth in the US generics market. What are your thoughts on the new R&D pipeline?',
    stockSymbol: 'SUNPHARMA',
    stockChangePercent: -0.74,
    tags: ['Pharma', 'Earnings', 'SUNPHARMA'],
    source: 'User Generated',
    likes: 64,
    comments: 9,
    reposts: 4,
    category: 'Fiat',
  },
  {
    id: 'post7',
    user: {
      name: 'NFT Collector',
      username: '@NFT_Guru',
      avatarUrl: 'https://placehold.co/40x40.png?text=NG',
    },
    timestamp: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(), // 15 hours ago
    content: 'The floor price for Bored Ape Yacht Club (BAYC) is holding steady. Still a blue-chip NFT project in my opinion. #NFT #BAYC',
    imageUrl: 'https://placehold.co/600x600.png',
    imageAiHint: 'ape avatar illustration',
    stockSymbol: 'BAYC',
    stockChangePercent: -1.9,
    tags: ['NFT', 'Collectibles'],
    source: 'User Generated',
    likes: 99,
    comments: 31,
    reposts: 11,
    category: 'Web3',
  },
  {
    id: 'research_wealth_2',
    user: {
        name: 'SIM Research Desk',
        username: '@SIM_Research',
        avatarUrl: 'https://placehold.co/40x40.png?text=SR',
    },
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    content: 'For investors with a low-risk appetite, the SBI Magnum Gilt Fund offers a stable return by investing in government securities. A good addition to a conservative portfolio. #Gilt #DebtFunds',
    tags: ['Debt', 'Mutual Funds', 'Low Risk'],
    source: 'SIM Research',
    likes: 45,
    comments: 8,
    reposts: 5,
    category: 'Wealth',
  },
];
