
import type { Stock } from '@/types';

export const mockCryptoMutualFunds: Stock[] = [
  { 
    id: 'cmf1', 
    symbol: 'CRYPINNO', 
    name: 'Crypto Innovators Fund Direct-Growth', 
    price: 25.50, // This represents NAV for MFs
    change: 0.75, 
    changePercent: 3.03, 
    exchange: 'Crypto MF', 
    sector: 'Thematic', 
    riskLevel: 'Very High',
    category: 'Thematic',
    annualisedReturn: 40.57,
    navDate: '20-Jun-2025',
    rating: 'NA',
    minSipAmount: 500,
    fundSize: '5,258 Cr',
    holdingsCount: 26,
    aboutCompany: 'An open-ended thematic mutual fund scheme investing in a diversified portfolio of companies that are participating in and benefiting from the crypto and blockchain innovation ecosystem.',
  },
  { 
    id: 'cmf2', 
    symbol: 'DEFIADV', 
    name: 'DeFi Advantage Fund Direct-Growth', 
    price: 18.20, 
    change: -0.15, 
    changePercent: -0.82, 
    exchange: 'Crypto MF', 
    sector: 'DeFi',
    riskLevel: 'Very High',
    category: 'Sectoral',
    annualisedReturn: 25.10,
    navDate: '20-Jun-2025',
    rating: 'NA',
    minSipAmount: 1000,
    fundSize: '2,100 Cr',
    holdingsCount: 18,
    aboutCompany: 'An open-ended sectoral mutual fund scheme investing in a diversified portfolio of decentralized finance (DeFi) protocols and applications on various blockchains.',
  },
  { 
    id: 'cmf3', 
    symbol: 'BLOCKCHAINPL', 
    name: 'Blockchain Plus Fund Direct-Growth', 
    price: 32.80, 
    change: 1.10, 
    changePercent: 3.46, 
    exchange: 'Crypto MF', 
    sector: 'Infrastructure',
    riskLevel: 'High',
    category: 'Thematic',
    annualisedReturn: 35.20,
    navDate: '20-Jun-2025',
    rating: 'NA',
    minSipAmount: 500,
    fundSize: '8,500 Cr',
    holdingsCount: 35,
    aboutCompany: 'An open-ended thematic mutual fund scheme investing in companies providing blockchain infrastructure, including layer-1s, layer-2s, and interoperability solutions.',
  },
];
