
import type { CorporateEvent } from '@/types';

export const mockEvents: CorporateEvent[] = [
  {
    id: 'evt1',
    companyName: 'U.P. Hotels Ltd.',
    date: '2025-07-27',
    dateType: 'Board Meet Date',
    tags: ['BM', 'Delisting'],
    description: 'Voluntary Delisting of Shares',
  },
  {
    id: 'evt2',
    companyName: 'Gordon Crest Education',
    date: '2025-07-28',
    dateType: 'Board Meet Date',
    tags: ['Results'],
    description: 'Quarterly Results',
  },
  {
    id: 'evt3',
    companyName: 'Bharat Parenterals Ltd.',
    date: '2025-07-23',
    dateType: 'Board Meet Date',
    tags: ['Results', 'AGM'],
    description: 'Quarterly Results & AGM',
  },
  {
    id: 'evt4',
    companyName: 'Benero Bearings & Pistons Ltd.',
    date: '2025-07-28',
    dateType: 'Board Meet Date',
    tags: ['Results'],
    description: 'Audited Results',
  },
  {
    id: 'evt5',
    companyName: 'Jonjua Overseas Ltd.',
    date: '2025-07-23',
    dateType: 'EX-Date',
    tags: ['Bonus'],
    description: 'Bonus - Bonus issue of equity shares in the ratio of 1:20 of Rs. 10/-',
  },
  {
    id: 'evt6',
    companyName: 'Ashapuri Gold Ornament Ltd.',
    date: '2025-07-28',
    dateType: 'Board Meet Date',
    tags: ['Results', 'AGM'],
    description: 'Quarterly Results & AGM',
  },
  {
    id: 'evt7',
    companyName: 'Neetu Tools Ltd.',
    date: '2025-07-23',
    dateType: 'Board Meet Date',
    tags: ['Results'],
    description: 'Audited Results',
  },
  {
    id: 'evt8',
    companyName: 'Trident Lifeline Ltd.',
    date: '2025-07-28',
    dateType: 'Board Meet Date',
    tags: ['Results'],
    description: 'Quarterly Results',
  },
  {
    id: 'evt9',
    companyName: 'BMW Industries Ltd.',
    date: '2025-07-23',
    dateType: 'Board Meet Date',
    tags: ['Results'],
    description: 'Quarterly Results',
  },
  {
    id: 'evt10',
    companyName: 'Mocfos Ltd.',
    date: '2025-07-28',
    dateType: 'Board Meet Date',
    tags: ['Results'],
    description: 'Quarterly Results',
  },
  {
    id: 'evt11',
    companyName: 'GTV Engineering Ltd.',
    date: '2025-07-23',
    dateType: 'EX-Date',
    tags: ['Split'],
    description: 'Split - Stock split from Rs. 10/- to Rs. 2/-',
  },
  {
    id: 'evt12',
    companyName: 'Shyam Metalics and Energy Ltd.',
    date: '2025-07-28',
    dateType: 'EX-Date',
    tags: ['Dividend'],
    description: 'INTERIM - Re 1.8 per share(18% on paid up equity)Interim Dividend',
  },
  {
    id: 'evt13',
    companyName: 'Crisil Ltd.',
    date: '2025-07-23',
    dateType: 'EX-Date',
    tags: ['Dividend'],
    description: 'INTERIM - Rs.9 per share(900%)Interim Dividend',
  },
  {
    id: 'evt14',
    companyName: 'Wipro Ltd.',
    date: '2025-07-28',
    dateType: 'EX-Date',
    tags: ['Dividend'],
    description: 'INTERIM - Re 1 per share(50%)Interim Dividend',
  },
  {
    id: 'evt15',
    companyName: 'EIH Associated Hotels Ltd.',
    date: '2025-07-28',
    dateType: 'EX-Date',
    tags: ['Dividend'],
    description: 'FINAL - Rs.3.5 per share(35%)Final Dividend',
  },
  {
    id: 'evt16',
    companyName: 'Cosmo First Ltd.',
    date: '2025-07-28',
    dateType: 'EX-Date',
    tags: ['Dividend'],
    description: 'FINAL - Rs.5 per share(50%)Final Dividend',
  },
  {
    id: 'evt17',
    companyName: 'DLF Ltd.',
    date: '2025-07-28',
    dateType: 'EX-Date',
    tags: ['Dividend'],
    description: 'FINAL - Rs.5 per share(250%)Final Dividend',
  },
];
