
import type { InsiderTrade } from '@/types';

export const mockInsiderTrades: InsiderTrade[] = [
    {
        id: 'it1',
        companyName: 'Mas Financial Services Ltd.',
        date: '28 Jul ‘25',
        insiderName: 'Estate of Mukesh Chimanlal',
        insiderRelation: 'Insider',
        quantity: 4838038,
        avgPrice: 0, // Not provided
        percentTraded: 26.66,
        transactionType: 'Acquisition',
        transactionMode: 'Off Market',
    },
    {
        id: 'it2',
        companyName: 'Yash Highvoltage Ltd.',
        date: '28 Jul ‘25',
        insiderName: 'ATUL G. SHAH',
        insiderRelation: 'Insider',
        quantity: 5000,
        avgPrice: 462,
        percentTraded: 0.02,
        transactionType: 'Acquisition',
        transactionMode: 'Market Purchase',
    },
    {
        id: 'it3',
        companyName: 'Pratiksha Chemicals Ltd.',
        date: '28 Jul ‘25',
        insiderName: 'HARISH K. BHATT',
        insiderRelation: 'Insider',
        quantity: 514450,
        avgPrice: 20,
        percentTraded: 9.24,
        transactionType: 'Disposal',
        transactionMode: 'Market Sale',
    },
     {
        id: 'it4',
        companyName: 'Authum Investment...',
        date: '25 Jul ‘25',
        insiderName: 'Mentor Capital Limited',
        insiderRelation: 'Insider',
        quantity: 5800000,
        avgPrice: 2253.6,
        percentTraded: 3.41,
        transactionType: 'Disposal',
        transactionMode: 'Market Sale',
    },
     {
        id: 'it5',
        companyName: 'Go Fashion (India) Ltd.',
        date: '26 Jul ‘25',
        insiderName: 'RAHUL SARAOGI',
        insiderRelation: 'Insider',
        quantity: 1116848,
        avgPrice: 882.5,
        percentTraded: 2.07,
        transactionType: 'Revoke',
        transactionMode: 'Pledge Released',
    },
];
