
import type { PriceAlert } from '@/types';

export const mockPriceAlerts: PriceAlert[] = [
  {
    id: 'alert1',
    instrumentName: 'Infosys Ltd.',
    symbol: 'INFY',
    targetPrice: 1400.00,
    condition: 'Above',
    currentPrice: 1350.00,
    status: 'Active',
    createdDate: '2024-01-01',
    exchange: 'NSE',
    assetType: 'Stock',
    notes: 'Check for breakout potential.',
  },
  {
    id: 'alert2',
    instrumentName: 'NIFTY 50 Index',
    symbol: 'NIFTY',
    targetPrice: 21000.00,
    condition: 'Below',
    currentPrice: 18250.75,
    status: 'Active',
    createdDate: '2023-12-15',
    exchange: 'NSE',
    assetType: 'Index',
  },
  {
    id: 'alert3',
    instrumentName: 'Bitcoin',
    symbol: 'BTC',
    targetPrice: 2500000.00,
    condition: 'Below',
    currentPrice: 2400000.00,
    status: 'Triggered',
    createdDate: '2023-11-20',
    exchange: 'Crypto',
    assetType: 'Crypto',
  },
  {
    id: 'alert4',
    instrumentName: 'BANKNIFTY JAN Future',
    symbol: 'BANKNIFTYJANFUT',
    targetPrice: 47600.00,
    condition: 'Above',
    currentPrice: 47500.75,
    status: 'Cancelled',
    createdDate: '2023-10-10',
    exchange: 'NFO',
    assetType: 'Future',
  },
];
